# Generated by Django 4.1.2 on 2022-10-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_answermodel_tone_alter_questionmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermodel',
            name='tone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
