# Generated by Django 4.1.2 on 2022-10-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_answermodel_tone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermodel',
            name='tone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
