# Generated by Django 4.1.2 on 2022-10-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_alter_answermodel_tone'),
    ]

    operations = [
        migrations.AddField(
            model_name='answermodel',
            name='date',
            field=models.DateTimeField(default='2021-12-31 15:25:00+01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answermodel',
            name='question',
            field=models.CharField(default=11, max_length=300),
            preserve_default=False,
        ),
    ]
